# Generated by Django 4.2.7 on 2025-12-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
    ]
