{
 "title": "Payout-service",
 "time": { "from": "2025-12-09T19:39:14.287Z", "to": "2025-12-09T21:06:28.386Z" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Средняя скорость обработки запросов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_including_middlewares_seconds_sum[5m]) / rate(django_http_requests_latency_including_middlewares_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление памяти приложения",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Сколько файлов открыло приложение (файлы БД, логи и т.д.)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_open_fds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Логи celery-tasks",
   "type": "logs",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app\"} |= \"payout-tasks\"  "
    }
   ]
  },
  {
   "title": "Логи изменения статуса платежа",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app\"} |= \"payout-status\"  "
    }
   ]
  },
  {
   "title": "Логи api",
   "type": "logs",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app\"} |= \"payout-api\"  "
    }
   ]
  }
 ]
}